import { getServerSession } from "next-auth";
import { Providers } from "../app/Providers";

import SessionProvider from "./components/SessionProvider";
import { Footer } from "./components/Footer";
import NewNavBar from "./components/NewNavBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="bg-[#121212] text-white">
        <SessionProvider session={session}>
          <Providers>
            <NewNavBar />
            {children}
            <Footer />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
