import { getServerSession } from "next-auth";

import SessionProvider from "./components/SessionProvider";
import { Footer } from "./components/footer";
import NewNavBar from "./components/NewNavBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="h-screen">
      <body className="bg-[#121212] text-white min-h-[100vh]">
        <SessionProvider session={session}>
          <div className="flex flex-col justify-center items-center h-[800px] w-screen">
            <NewNavBar />
            {children}
            <Footer />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
